### ISSUE TITLE
Polls disappear after posting for regular users

### ISSUE THREAD

**Issue by AaronGiebelSandbox** [pupi1985/q2a-poll#1]
A regular registered user can create a poll in the editor as normal, but when they click the post button, poof! The poll is gone.

1) creating poll in post editor
<img width="280" alt="image" src="https://github.com/user-attachments/assets/f5aaa2ac-d2e8-4651-aa3f-4eb150cd364d" />

2) poll does not show up after posting
<img width="618" alt="Screenshot 2024-12-20 024728" src="https://github.com/user-attachments/assets/7f59dda5-1e17-43ab-baf5-f23af8311775" />

3) It works as normal for anyone with mod role or higher, just not for regular users. Note that I do have the correct perms:
<img width="586" alt="image" src="https://github.com/user-attachments/assets/652aad22-1b2b-4f63-8266-5c782c7694d1" />

4) Here, a poll created by a moderator shows up in the post just fine
<img width="572" alt="image" src="https://github.com/user-attachments/assets/10a6d267-5b65-4dd0-9583-8179c36d3838" />

Replicate this issue by attempting to post a poll as a standard user without mod perms.
PHP version is 8.2.26 but the issue did not correct when I went higher to 8.4.1
Question2answer is 1.8.8

TY!!

**Comment by pupi1985** [comment]
The issue comes when the question being post is moderated. Can you check if v2.4.4 fixes it?

https://github.com/pupi1985/q2a-poll/releases/latest

**Comment by AaronGiebelSandbox** [comment]
Fixed, ty so much for the fast response. You're a real one fr
